### ISSUE TITLE
[Feature suggestion] Drag & Drop ckpt to the executable scans it

### ISSUE THREAD

**Issue by etherealxx** [diStyApps/Stable-Diffusion-Pickle-Scanner-GUI#2]
I've seen a model hash scanner with this feature. Also would be nice if we can drag & drop ckpt to the GUI to instantly scans it.

**Comment by diStyApps** [comment]
Hey,good idea i will look in to it, can you link the hash scanner?

**Comment by etherealxx** [comment]
https://github.com/Akegarasu/sd-model-hash

**Comment by diStyApps** [comment]
Thank you for your feature suggestion.
Unfortunately, I don't have time to work on it at the moment. However, I will consider adding this feature in a future update.
Thank you for your suggestion and for using the app.
