### ISSUE TITLE
[Bug] Corrupted zip file causes crash instead of failing gracefully.

### ISSUE THREAD

**Issue by ThomasWeber** [diStyApps/Stable-Diffusion-Pickle-Scanner-GUI#3]
Corrupted zip file causes crash instead of failing gracefully or notifying user.

How to reproduce:
Create a bad ckpt (such as by interrupting a merge), then scan a directory with it. You'll get an error about a bad zip file and the entire program will crash.

Expected behavior:
Notify the user that the ckpt is corrupted.

**Comment by diStyApps** [comment]
Thanks for opening this issue.
