### ISSUE TITLE
Error running on Mac OS 13.1 _tkinter.TclError: unknown option "-relief"

### ISSUE THREAD

**Issue by radfaraf** [diStyApps/Stable-Diffusion-Pickle-Scanner-GUI#4]
Not sure if it's supposed to work here (Mac OS 13.1), so I tried it to see -- got some errors that I fixed by installing more packages. 

Then got this error that I couldn't figure out with some searches:

python3 picklescan_gui.py

Mac OS Version is 13.1 and patch enabled so applying the patch
Applyting Mac OS 12.3+ Alpha Channel fix.  Your default Alpha Channel is now 0.99
Traceback (most recent call last):
  File "/Users/robertw/Stable-Diffusion-Pickle-Scanner-GUI/picklescan_gui.py", line 409, in <module>
    main() 
  File "/Users/robertw/Stable-Diffusion-Pickle-Scanner-GUI/picklescan_gui.py", line 222, in main
    widget.Widget.config(relief='flat')  
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-relief"

**Comment by diStyApps** [comment]
No its made for mac because i cant test on mac, but maybe it will work.

Try to comment out the widget in line 222: 

     "input_files_directory_widget"
      
if it wont work try to comment out :

in lines 227-228

     for widget in widgets:
        widget.Widget.config(relief='flat')

**Comment by radfaraf** [comment]
Commenting out the two lines in the second suggestion work though the line numbers given are 221-222 for me and not 227-228. 

I got it to scan my files as shown here:

https://prnt.sc/etPTPBzb8Tsl

**Comment by diStyApps** [comment]
Great, soon ill update fix,

If you can share what needed to get to to work on mac it will be great.
Thank you.

**Comment by radfaraf** [comment]
Here are instructions you can give people though they may not be perfect I am looking through command line logins of what I did and had to make a few attempts for some of them.

Download the files from here using:
git clone https://github.com/diStyApps/Stable-Diffusion-Pickle-Scanner-GUI

Change to the directory downloaded to run: python3 picklescan_gui.py     

You might get errors related to certain files.
If related to PySimpleGUI try: python3 -m pip install PySimpleGUI 
If related to tk/tkinter try: python3 -m pip install tkinter  
If you get an error that says "_tkinter.TclError: unknown option "-relief" "
then comment out in the file  picklescan_gui.py   by putting in # before the lines (currently lines 221-222 or closeby):
```
 for widget in widgets:
    widget.Widget.config(relief='flat')  
```

After doing each fix run this again and see what errors remain: python3 picklescan_gui.py   
You may need some other files/packages not mentioned here that you might be able to find with a google search on the messages.

**Comment by diStyApps** [comment]
Thank you for the instructions.
It looks like the problem may be related to installing packages.
One potential solution is to try installing miniconda, which is useful for managing different python environments.
There is a version for Mac available at the following link: https://docs.conda.io/en/latest/miniconda.html.
This may help to resolve the issue with packages.

And then clone the repository again and try the following steps:
Type the following command:
```
   cd into the Stable-Diffusion-Pickle-Scanner-GUI folder
```
Type the following command:
```
   conda env create -f conda.yaml
```
These steps should help to resolve any issues with the packages. 
Let me know if you have any further questions or need additional assistance.

ill update installation guide and if it working for mac users.

Thank you.

**Comment by radfaraf** [comment]
I can confirm the code update works now so I don't have to edit the files myself to comment out those lines. I don't know about the package issue though since I had already fixed all that manually. Probably best to see if anyone else who tries it on a Mac has an issue because it's fully working for me.

**Comment by diStyApps** [comment]
Great thank you.
