### ISSUE TITLE
Unable to scan hypernetworks ".pt" files.

### ISSUE THREAD

**Issue by falsonerd** [diStyApps/Stable-Diffusion-Pickle-Scanner-GUI#7]
![image](https://user-images.githubusercontent.com/50148645/208553499-f4058dd4-a319-439f-9fc1-285115f52921.png)
Fail to scan: Corrupted file......
As written on title, GUI cannot scan for hypernetworks .pt files.

**Comment by diStyApps** [comment]
Hi there,

Thank you for bringing this issue to my attention. 
.pt files are supported by the app. It's possible that the specific .pt file you're trying to scan is corrupted, which could be causing the issue.

Here is a list of the file types that the app should support:

``
  .bin, .pt, .pth, .ckpt, .pkl, pickle, .joblib, .dat, .data, .npy, .zip, and .npz.
``

I recommend trying to scan other .pt files to see if the issue persists. If the problem persists with all .pt files, 
or only this specific file, then give me more info about the file.

I hope this helps. Let me know if you have any further questions or if there's anything else I can do to assist you.

**Comment by falsonerd** [comment]
I'll close this issue for now, since I need to do more testings.
.pt files from a different source were able to be scanned just fine though....
If this happens again I will re-open the issue with more info.
