### ISSUE TITLE
[Feature Request] Include safetensors Model Format for Scanning

### ISSUE THREAD

**Issue by KingJigglypuff** [diStyApps/Stable-Diffusion-Pickle-Scanner-GUI#8]
Right now. the pickle scanner only scans ckpt models, so I'd like to put in a feature request to include safetensors models to include in pickle scanning.

**Comment by diStyApps** [comment]
SafeTensors does not contain pickles, it is a pure data format.

**Comment by KingJigglypuff** [comment]
Understood, thanks for responding.
